### ISSUE TITLE
[Spoiler] mechanic doesn't work on Platinum Star and Uppskeruvel.

### ISSUE THREAD

**Issue by AdvintasAHAT86420** [pcrain/GungeonCraft#10]
The Platinum Star and Uppskeruvel do not appear to visualize the mastery ritual, let alone indicate the circles that comprise it.

I even use a blank to test whether the Platinum Star and Uppskeruvel will transform into their mastery forms.

Here's a video. (I don't know how to add a spoiler tag to the video, so sorry.)

https://github.com/user-attachments/assets/4fa6998a-6b02-49a6-8de3-1c91c5f558ac

**Comment by pcrain** [comment]
So, to quote [REDACTED], "something cool might happen depending on the combined strength of the guns." The "combined strength" part is important, and is referring to the fact that at least 1 of the 3 guns being sacrificed need to be the same quality (or higher) as the gun receiving as the mastery (with quality basically being "the color of chest you find the gun in"). In your example, you're using 2 D-tier guns and 1 B-tier gun, which will work for Pincushion (which is D-tier), but won't work for Uppskeruvel or Platinum Star (which are both A-tier). You could, for instance, confirm that the ritual works by using a Fightsabre as one of the components. 

All that said, the reason the hint is so vague with "combined strength" is because Gungeon doesn't actually directly reference gun quality anywhere. I'll try to work in a mention of "gun quality" or "chest color" into the hint next update so it's less confusing, sorry about that. :sweat_smile: 

On the flip side, do you by any chance have your graphics settings on low? The ritual usually has some extra particle effects, but apparently they don't play on lower graphics settings.


https://github.com/user-attachments/assets/e67d6f6f-e854-4312-b108-e726234c9007

**Comment by AdvintasAHAT86420** [comment]
Thank you very much for clarifying and resolving my confusion.

And yes, I have my graphic settings set to low because I have a low-end laptop.
