### ISSUE TITLE
Femtobyte Gun Bugs

### ISSUE THREAD

**Issue by Antiiilluminati** [pcrain/GungeonCraft#11]
This gun is really, really cool, it does come with a few issues however.

This gun cannot damage enemies in minecarts
This gun cannot store or unlock the yellow "revive" chests (multiplayer only)
Also, I havent tested this but can this gun activate table techs by re-spawning tables over and over again?

Man, I love this gun

**Comment by pcrain** [comment]
> This gun cannot damage enemies in minecarts 

That one's definitely a bug, whoops. :open_mouth: I'll look into it!

> This gun cannot store or unlock the yellow "revive" chests (multiplayer only). 

That one is intentional, the game code is a bit dodgy around that kind of thing and things would probably break horrendously if I tried to do that. :sweat_smile: I'll look into it and see if it's fixable, but probably not.

> Also, I havent tested this but can this gun activate table techs by re-spawning tables over and over again?

Whoops...it sure can, that's a little busted. I might tone that down or make it a synergy or something, good catch, thanks. :sweat_smile: 

> Man, I love this gun

Glad you're enjoying it. :smile:

**Comment by pcrain** [comment]
Couldn't do anything about the co-op chest unfortunately, but the minecart and table tech issues are fixed in 1.17.0! :smile:
