### ISSUE TITLE
Suggestions for Hecked Mode and a Bug Report

### ISSUE THREAD

**Issue by dIDMas** [pcrain/GungeonCraft#14]
Hi pcrain!

After playing for 2 hours in Hecked Mode with the "give armor 200" command, I noticed that every random gun-wielding enemy essentially turns into an upgraded version of "AK47 Bulletkin." After entering a room, the gameplay devolves into constantly circling around enemies or positioning yourself behind cover to shoot, since most of the weapons make it nearly impossible to dodge through the bullet patterns. Compared to the vanilla, it loses much of the bullet hell gameplay's core appeal and fun.

Some specific types of guns feel particularly overpowered and make the game unnecessarily frustrating. I'll break them down into categories:

1. The Fat Line: Bullets that come from the wall are unavoidable.
2. High-speed, bouncing projectiles: A prime example is the Super Meat Gun, where the entire room fills with bouncing bullets. It reminds me of the "Rainbow Chest Mimic" from an old mod.
3. Extremely fast projectiles: Examples include Railgun, Trident, and Eye of the Beholster.
4. High-rate-of-fire and spread guns: A prime example is the Vulcan Cannon.
5. Homing projectiles: Examples include Compressed Air Tank, Bee Hive, and Bait Launcher.

If any of the above guns appear in a room, it's almost guaranteed to cause unavoidable damage. These guns make up a significant portion of the gun pool, which is the biggest issue with Hecked Mode. Because of this, it is impossible for most players to enjoy a normal gameplay experience.

However, the concept of this mode is truly unique among all mods, and I feel that the difficulty shouldn't be set so high that it becomes inaccessible to players.

Here are a few personal suggestions for the mode:

1. Reduce the bullet speed of random gun-wielding enemies: With slower projectiles, guns in categories 2 and 4 would become dodgeable.
2. Significantly lower the spawn chance of the above gun types: In a given floor, encountering no more than 4 enemies with these guns would make the game more manageable. Four guaranteed hits per floor is still challenging but not impossible to play through.
3. Increase the spawn chance of guns like Bubble Blaster, Stone Dome (its projectile behavior is unique in that it circles around, which is similar to Cannon's attack in the vanilla and feels fun), Crown of Guns, Balloon Gun, Mr. Accretion Jr., Screecher, Helix, RPG, Lil' Bomber, Grasschopper, Fossilized Gun, Molotov Launcher, Quad Laser, Gungeon Ant. These guns have unique or rarely seen projectile mechanics in the vanilla, and increasing their spawn rate would add more variety and fun to the gameplay.
4. If possible, equip the Shotgunkin exclusively with shotguns, retaining their original mechanics. For example, maintain the Blue Shotgunkin's slower projectile speed and higher spread and the Veteran Shotgunkin's predictive shot pattern. 
5. If possible, I hope the number of enemies with random guns can be customized: For example, make it so that only 1 out of every 10 gun-wielding enemies uses a random gun. When introducing players to a new game, it's best to follow a progression principle—starting easy and gradually increasing in difficulty. Most players won't stick around if they're immediately overwhelmed by every enemy wielding an overpowered custom gun.

Finally, there are also some audio bugs with Gunzheng, The Fat Line, and Abyssal Tentacle. These are the three guns I've encountered so far where, after their wielders die, the firing sound persists, which is very noisy.

**Comment by pcrain** [comment]
Hiya @dIDMas ! :smile: 

So, first off, the audio bugs: the audio glitching with certain guns has been something I've known about for a while. I've tried to remove most of the noisy guns from the gun pool, but it seems like new ones keep popping up. It was really hard to fix when I was newer to Gungeon modding last year, but I might take another swing at it in the near future and see if I can resolve it and add some of the guns back into the loot pool. :slightly_smiling_face:  As for Hecked Mode itself, it has a bit of a history, but I'll try to address as many of your points as I can.

The main premise of Hecked Mode is "what if enemies had access to the same guns with the same stats as the Player?" With that premise in mind, it is very intentionally unfair and unforgiving by design, and was never intended to be beatable in the first place! It started as a proof of concept / joke mode while I was trying to figure out how to change guns on enemies, and it kind of evolved from there. I know of exactly two people that have ever beaten the Dragun, and only one has beaten the Lich; I personally have never gotten past the 2nd floor. So the facts that 1) it was never intended to beaten and 2) that two people have beaten it anyway is enough to dissuade me from making the existing Hecked mode any easier. :sweat_smile: 

All of that said, I've also been aware from the beginning that with a couple of tweaks here and there, Hecked Mode has genuine potential to be fun for a wider audience of people. There's a reason why the option for enabling it is a scroll box rather than a checkbox. :wink:  There have been plans for several variations of Hecked Mode since the beginning, and I just never got around to implementing them fully. Some ideas that are in varying states of completion include:

- Retrashed Mode: an even harder and more unforgiving variant of Hecked Mode (if you can believe it) that gives every single enemy a gun and prevents various cheese strats (named after the first / only person to beat Hecked Mode without Rainbow Run strats)
- Slightly Hecked Mode: similar to what you suggested, an easier variant of Hecked Mode where enemies cannot be given any "unfair" guns (I've also toyed around with the idea of letting them drop their guns for the player to use, a proof of concept mechanic that's already been implemented in the Tranquilizer gun)
- Grenade Mode: the player and every enemy is given an infinite ammo Grenade Launcher, which allows for fun team kill shenanigans
- Molotov Mode: the player and every enemy is given an infinite ammo Molotov Launcher, which allows for some fun tactical / positional play

To address your individual suggestions:

> 1. Reduce the bullet speed of random gun-wielding enemies.

The premise of Hecked Mode is that enemies wield guns with the same stats as they'd have if the player were wielding them (besides having infinite ammo). So I'm not keen on changing the actual mechanics of any of the guns in any variant of Hecked Mode.

> 2. Significantly lower the spawn chance of the above gun types.

This one's absolutely reasonable for Slightly Hecked mode, I can definitely tone down / completely remove the more unfair ones for that.

> 3. Increase the spawn chance of guns with unique mechanics.

This could definitely be fun in a variant!

> 4. Equip Shotgunkin exclusively with shotguns.

Honestly I might just add giving certain enemies thematic guns a (toggleable) option for base GungeonCraft. :open_mouth: 

> 5. Customize the number of enemies with random guns.

I'll have to consider this more, it might be interesting having this as a separate option for all variants of Hecked Mode. I'll definitely think about it!

Anywho thanks for all the feedback! :smile:  I'll keep this issue open at least until the audio bugs are resolved, and in the near future I'll finished up all the Hecked Mode variants I've had planned for a while and try to incorporate your suggestions as appropriate. But the current classic Hecked Mode as it exists right now will most likely remain at its current level of difficulty.

**Comment by dIDMas** [comment]
I had no idea the Tranquilizer worked like that! Not written in the Ammonomicon, I would have thought it was just an ordinary STUN gun, like other mods with only a stun effect.😬 After trying it out, I have to say, it's incredibly powerful. I can grab ak47, magnum, winchester and sniper easily! I believe upgrading this gun to A Quality is completely reasonable.

@pcrain , I'm really happy that the developer took the time to read and respond to my suggestions seriously. Also, the development directions you mentioned all sound super interesting, I'm really looking forward to the day Hecked Mode is fully fleshed out. Thank you so much for your contributions to the Gungeon modding community! 😃

**Comment by pcrain** [comment]
Audio bug should be fixed, and I finally finished up those variants I mentioned. :slightly_smiling_face: Hope one or two of them suit your fancy. :smile:
