### ISSUE TITLE
Alien Nailgun Mimics deal no damage

### ISSUE THREAD

**Issue by Antiiilluminati** [pcrain/GungeonCraft#9]
When spawning in a blue chest mimic (I havent tried this with any other types of mimic) the minic will walk and shoot like a normal mimic, but the bullets phase through enemies. As far as I know, this doesn't happen with any other enemy that I tried this with (shotgun kin family, bullet kin, blob cube)

Also, I don't know if this is intentional or not but sometimes allies can spawn in jammed

**Comment by Antiiilluminati** [comment]
Just found out the allies you summon can be jammed via goop & the cursed slime from another mod, sometimes they just spawn in jammed tho

**Comment by Antiiilluminati** [comment]
Does killing a boss let you spawn it in with the gun?

**Comment by pcrain** [comment]
> When spawning in a blue chest mimic (I havent tried this with any other types of mimic) the minic will walk and shoot like a normal mimic, but the bullets phase through enemies. As far as I know, this doesn't happen with any other enemy that I tried this with (shotgun kin family, bullet kin, blob cube)

Yeah that doesn't sound good. :open_mouth: I'll look into it. :slightly_smiling_face: 
 
> Also, I don't know if this is intentional or not but sometimes allies can spawn in jammed

That's definitely not intentional, probably also a bug, thanks for letting me know. :sweat_smile: 

> Does killing a boss let you spawn it in with the gun?

No, bosses are immune because spawning bosses outside boss rooms causes biiiiiig problems. :sweat_smile: 

Thanks again for the report, I'll fix it by the next update. :slightly_smiling_face:

**Comment by pcrain** [comment]
Fixed! :smile:
